export enum ProgLangsEnum {
  JAVA = "Java",
  JAVASCRIPT = "JavaScript",
  PYTHON = "Python",
  C = "C",
  CPP = "C++",
  RUST = "Rust",
  PHP = "PHP",
  GO = "Go",
  CSHARP = "C#",
  FSHARP = "F#",
  SWIFT = "Swift",
  DART = "Dart",
  KOTLIN = "Kotlin",
  SCALA = "Scala",
  SOLIDITY = "Solidity",
  HASKEL = "Haskel",
  RUBY = "Ruby",
  LUA = "Lua",
  JULIA = "Julia",
  R = "R",
  OBJECTIVEC = "Objective-C",
  BASIC = "Basic",
  DELPHI = "Delphi",
  FORTRAN = "Fortran",
}

export enum TechnologiesEnum {
  DOCKER = "Docker",
  KUBERNETES = "Kubernetes",
  REDIS = "Redis",
  KAFKA = "Kafka",
  RABBITMQ = "RabbitMQ",
  MYSQL = "MySQL",
  POSTGRESQL = "PostgreSQL",
  MONGODB = "MongoDB",
  GRAPHQL = "GraphQL",
  ELK = "ELK",
  CLICKHOUSE = "ClickHouse",
}

export enum FrameworksEnum {
  REACTJS = "ReactJS",
  VUEJS = "VueJS",
  GIN = "Gin",
  LARAVEL = "Laravel",
  SYMFONY = "Symfony",
  EXPRESSJS = "ExpressJS",
  NODEJS = "NodeJS",
  TENSORFLOW = "Tensorflow",
  PYTORCH = "Pytorch",
  NEXTJS = "NextJS",
  FLASK = "Flask",
}
